# Listener MQTT padrao
listener 1883
protocol mqtt

# Listener WebSocket (para browser/painel)
listener 9001
protocol websockets

# Autenticacao obrigatoria
allow_anonymous false
password_file /etc/mosquitto/passwd

# Logs
log_dest stdout
log_type all

# Persistencia
persistence true
persistence_location /var/lib/mosquitto/

# Keep alive
keepalive_interval 60
