# Configurações Básicas
listener 1883
protocol mqtt

listener 9001
protocol websockets

# Segurança
allow_anonymous false
password_file /etc/mosquitto/passwd

# Persistência e Logs
persistence true
persistence_location /var/lib/mosquitto/
log_dest stdout

# Configurações de Conexão
keepalive_interval 60
