# Conexão interna para Node-RED e ESP32
listener 1883 0.0.0.0
protocol mqtt

# Conexão para o Painel HTML (WebSockets)
listener 9001 0.0.0.0
protocol websockets

allow_anonymous false
password_file /etc/mosquitto/passwd
